export const ROUTE_REQUEST = "ROUTE_REQUEST";
export const PROCESS_DATA = "PROCESS_DATA";
export const BUILD_TABLE = "CREATE_APPEND";
export const BUILD_USER = "BUILD_USER";
export const BUILD_USER_LOADING = "BUILD_USER_LOADING";
export const BUILD_USER_SUCCESS = "BUILD_USER_SUCCESS";
export const ALL_ROLES = "ALL_ROLES";
export const EDIT_USER = "EDIT_USER";
